# Generated by Django 5.0.6 on 2024-06-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='title',
            new_name='task_name',
        ),
    ]
